// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc3Cv94F37WOb4DR5pz0Wp9eOo2DTUV84',
    appId: '1:596418964902:web:fb1263e7b3084da4447367',
    messagingSenderId: '596418964902',
    projectId: 'stronger-f7c9c',
    authDomain: 'stronger-f7c9c.firebaseapp.com',
    storageBucket: 'stronger-f7c9c.firebasestorage.app',
    measurementId: 'G-45JV2WM0NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXbm7gQ2fHqRR9UKlmxvnlAZHQXaEkUQ',
    appId: '1:596418964902:android:32558367c60a1f0f447367',
    messagingSenderId: '596418964902',
    projectId: 'stronger-f7c9c',
    storageBucket: 'stronger-f7c9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLIZPAibTIQG_J0WGxWi_Frqull5Lv4BQ',
    appId: '1:596418964902:ios:a5f3c5c97eeae0f3447367',
    messagingSenderId: '596418964902',
    projectId: 'stronger-f7c9c',
    storageBucket: 'stronger-f7c9c.firebasestorage.app',
    iosBundleId: 'com.example.businessIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLIZPAibTIQG_J0WGxWi_Frqull5Lv4BQ',
    appId: '1:596418964902:ios:a5f3c5c97eeae0f3447367',
    messagingSenderId: '596418964902',
    projectId: 'stronger-f7c9c',
    storageBucket: 'stronger-f7c9c.firebasestorage.app',
    iosBundleId: 'com.example.businessIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc3Cv94F37WOb4DR5pz0Wp9eOo2DTUV84',
    appId: '1:596418964902:web:74853d544e9cb366447367',
    messagingSenderId: '596418964902',
    projectId: 'stronger-f7c9c',
    authDomain: 'stronger-f7c9c.firebaseapp.com',
    storageBucket: 'stronger-f7c9c.firebasestorage.app',
    measurementId: 'G-HQVQTHKL81',
  );
}
